In [1]:
import re

In [2]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

print(len(raw_text))
print(raw_text[:150])

20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of


In [3]:
text = "Hello, world. This, is a test."
print(re.split(r"[,.|\s]", text))

['Hello', '', 'world', '', 'This', '', 'is', 'a', 'test', '']


In [17]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)


The 

re.split()

 function is used to split the 

raw_text

 string wherever the pattern specified in the regular expression is found. The regular expression pattern `r"[,.:;?_!()\']|--|\s"` includes several delimiters:
- `[,.:;?_!()\']` matches any single character within the square brackets, such as commas, periods, colons, semicolons, question marks, underscores, exclamation marks, parentheses, and single quotes.
- `|--` matches the double hyphen (`--`).
- `|\s` matches any whitespace character, including spaces, tabs, and newlines.

By using this pattern, the 

re.split()

 function will break the 

raw_text

 into tokens whenever it encounters any of these delimiters. The result is stored in the variable 

preprocessed

In [18]:
preprocessed = [item.strip() for item in preprocessed if item.strip()] # if item.strip() removes empty strings 

In [19]:
print(len(preprocessed))
print(preprocessed[:30])

4690
['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


In [22]:
all_words = set(preprocessed)
all_words = sorted(all_words)
all_words

['!',
 '"',
 "'",
 '(',
 ')',
 ',',
 '--',
 '.',
 ':',
 ';',
 '?',
 'A',
 'Ah',
 'Among',
 'And',
 'Are',
 'Arrt',
 'As',
 'At',
 'Be',
 'Begin',
 'Burlington',
 'But',
 'By',
 'Carlo',
 'Chicago',
 'Claude',
 'Come',
 'Croft',
 'Destroyed',
 'Devonshire',
 'Don',
 'Dubarry',
 'Emperors',
 'Florence',
 'For',
 'Gallery',
 'Gideon',
 'Gisburn',
 'Gisburns',
 'Grafton',
 'Greek',
 'Grindle',
 'Grindles',
 'HAD',
 'Had',
 'Hang',
 'Has',
 'He',
 'Her',
 'Hermia',
 'His',
 'How',
 'I',
 'If',
 'In',
 'It',
 'Jack',
 'Jove',
 'Just',
 'Lord',
 'Made',
 'Miss',
 'Money',
 'Monte',
 'Moon-dancers',
 'Mr',
 'Mrs',
 'My',
 'Never',
 'No',
 'Now',
 'Nutley',
 'Of',
 'Oh',
 'On',
 'Once',
 'Only',
 'Or',
 'Perhaps',
 'Poor',
 'Professional',
 'Renaissance',
 'Rickham',
 'Riviera',
 'Rome',
 'Russian',
 'Sevres',
 'She',
 'Stroud',
 'Strouds',
 'Suddenly',
 'That',
 'The',
 'Then',
 'There',
 'They',
 'This',
 'Those',
 'Though',
 'Thwing',
 'Thwings',
 'To',
 'Usually',
 'Venetian',
 'Victor',
 '

In Python, `set` and `dict` are both built-in data structures, but they serve different purposes and have distinct characteristics:

### Set
- **Definition**: A `set` is an unordered collection of unique elements.
- **Syntax**: Defined using curly braces `{}` or the `set()` function.
  ```python
  my_set = {1, 2, 3}
  my_set = set([1, 2, 3])
  ```
- **Uniqueness**: Automatically removes duplicate elements.
  ```python
  my_set = {1, 2, 2, 3}  # Result: {1, 2, 3}
  ```
- **Mutability**: Sets are mutable; you can add or remove elements.
  ```python
  my_set.add(4)
  my_set.remove(2)
  ```
- **Operations**: Supports mathematical set operations like union, intersection, difference.
  ```python
  set1 = {1, 2, 3}
  set2 = {3, 4, 5}
  union_set = set1 | set2  # {1, 2, 3, 4, 5}
  intersection_set = set1 & set2  # {3}
  ```

### Dictionary
- **Definition**: A `dict` (dictionary) is an unordered collection of key-value pairs.
- **Syntax**: Defined using curly braces `{}` with key-value pairs or the `dict()` function.
  ```python
  my_dict = {'a': 1, 'b': 2, 'c': 3}
  my_dict = dict(a=1, b=2, c=3)
  ```
- **Key-Value Pairs**: Each key is unique and maps to a value.
  ```python
  my_dict = {'a': 1, 'b': 2, 'b': 3}  # Result: {'a': 1, 'b': 3}
  ```
- **Mutability**: Dictionaries are mutable; you can add, remove, or modify key-value pairs.
  ```python
  my_dict['d'] = 4
  del my_dict['a']
  my_dict['b'] = 5
  ```
- **Access**: Values are accessed using keys.
  ```python
  value = my_dict['b']  # 5
  ```

### Summary
- **Set**: Unordered collection of unique elements, used for membership testing and set operations.
- **Dict**: Unordered collection of key-value pairs, used for fast lookups, additions, and deletions based on keys.

In [23]:
vocab_size = len(all_words)
print(vocab_size)

1130


In [24]:
type(all_words)

list

In [25]:
vocab = {token: integer for integer, token in enumerate(all_words)}
for i, item in enumerate(vocab.items()):
    print(item)
    if i > 10:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)


In [27]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {integer: token for token, integer in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        return [self.str_to_int[token] for token in preprocessed]
    
    def decode(self, ids):
        text = " ".join([self.int_to_str[id] for id in ids])
        text = re.sub(r'\s([,.:;?_!"()\']|--)', r'\1', text) # remove space before punctuation
        return text

In [29]:
tokenizer = SimpleTokenizerV1(vocab)
text = """"It's the last he painted, you know,"
        Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


In [30]:
print(tokenizer.decode(ids))

" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


## Byte pairing encoding

In [8]:
from importlib.metadata import version
import tiktoken
print(version("tiktoken"))

0.8.0


In [33]:
tokenizer = tiktoken.get_encoding("gpt2")

In [44]:
text = ("Hello, do you like tea? <|endoftext|> Yes, I do "
        "of someunknownPlace.")

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 3363, 11, 314, 466, 286, 617, 34680, 27271, 13]


In [45]:
strings = tokenizer.decode(integers)
print(strings)

Hello, do you like tea? <|endoftext|> Yes, I do of someunknownPlace.


In [46]:
exercise = "Akwirw ier"
integers = tokenizer.encode(exercise)
print(integers)

[33901, 86, 343, 86, 220, 959]


In [47]:
strings = tokenizer.decode(integers)
print(strings)

Akwirw ier


In [48]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [49]:
enc_sample = enc_text[50:]
context_size = 4
x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]
print(x)
print(y)

[290, 4920, 2241, 287]
[4920, 2241, 287, 257]


In [51]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    target = enc_sample[i]
    print(context, "---->", target)
    context_words = tokenizer.decode(context)
    target_word = tokenizer.decode([target])
    print(context_words, "---->", target_word)

[290] ----> 4920
 and ---->  established
[290, 4920] ----> 2241
 and established ---->  himself
[290, 4920, 2241] ----> 287
 and established himself ---->  in
[290, 4920, 2241, 287] ----> 257
 and established himself in ---->  a


In [53]:
import sys

print(sys.version)

3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]


In [4]:
import torch
from torch.utils.data import Dataset, DataLoader

In [5]:
torch.cuda.is_available()

False

In [16]:
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt)

        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i+max_length]
            target_chunk = token_ids[i+1:i+max_length+1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids) # total number of rows in the dataset
    
    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx] # return a single row from the dataset
    

def create_dataloader_v1(txt, batch_size = 4, max_length = 256,
                         stride = 128, shuffle = True, drop_last = True, num_workers = 0):
    tokenizer = tiktoken.get_encoding("gpt2")
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
    dataloader  = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, drop_last=drop_last, num_workers=num_workers)
    return dataloader

In [17]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length = 4, stride=1, shuffle = False)
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [18]:
first_batch[0].shape

torch.Size([1, 4])

In [19]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [ ]:
dataloader_practice1 = create_dataloader_v1(raw_text, batch_size=1, max_length=2, stride=2, shuffle=False)
data_iter = iter(dataloader_practice1)
first_batch = next(data_iter)
print(first_batch) # first tensor is the input_ids and the second tensor is the target_ids
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 40, 367]]), tensor([[ 367, 2885]])]
[tensor([[2885, 1464]]), tensor([[1464, 1807]])]


In [24]:
dataloader_practice1 = create_dataloader_v1(raw_text, batch_size=2, max_length=8, stride=2, shuffle=False)
data_iter = iter(dataloader_practice1)
first_batch = next(data_iter)
print(first_batch) #  first tensor is the input_ids and the second tensor is the target_ids
second_batch = next(data_iter)
print(second_batch)

[tensor([[   40,   367,  2885,  1464,  1807,  3619,   402,   271],
        [ 2885,  1464,  1807,  3619,   402,   271, 10899,  2138]]), tensor([[  367,  2885,  1464,  1807,  3619,   402,   271, 10899],
        [ 1464,  1807,  3619,   402,   271, 10899,  2138,   257]])]
[tensor([[ 1807,  3619,   402,   271, 10899,  2138,   257,  7026],
        [  402,   271, 10899,  2138,   257,  7026, 15632,   438]]), tensor([[ 3619,   402,   271, 10899,  2138,   257,  7026, 15632],
        [  271, 10899,  2138,   257,  7026, 15632,   438,  2016]])]


## Create token embeddings

In [26]:
input_ids = [2, 3, 5, 1]
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [27]:
print(embedding_layer(torch.tensor(3)))

tensor([-0.4015,  0.9666, -1.1481], grad_fn=<EmbeddingBackward0>)


In [28]:
print(embedding_layer(torch.tensor(input_ids)))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [29]:
vocab_size = 50257 # BPE tokenizer vocab size
output_dim = 256 # embedding dimension
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [30]:
max_length = 4
dataloader = create_dataloader_v1(raw_text, batch_size = 8, max_length = max_length, stride = max_length, shuffle=False)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Token IDs:\n", inputs)
print("\nInputs shape: \n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape: 
 torch.Size([8, 4])


In [31]:
token_embeddings = token_embedding_layer(inputs)
print("\nToken embeddings shape: \n", token_embeddings.shape)


Token embeddings shape: 
 torch.Size([8, 4, 256])


In [33]:
token_embeddings[0] # first batch

tensor([[ 0.4913,  1.1239,  1.4588,  ..., -0.3995, -1.8735, -0.1445],
        [ 0.4481,  0.2536, -0.2655,  ...,  0.4997, -1.1991, -1.1844],
        [-0.2507, -0.0546,  0.6687,  ...,  0.9618,  2.3737, -0.0528],
        [ 0.9457,  0.8657,  1.6191,  ..., -0.4544, -0.7460,  0.3483]],
       grad_fn=<SelectBackward0>)

In [34]:
print(token_embeddings[0].shape)

torch.Size([4, 256])


In [35]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [37]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
